### ISSUE TITLE
[bug] fedora: cqlsh undefined symbol

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#202]
![image](https://github.com/user-attachments/assets/c791c8a6-8300-430a-89d2-45dbc4664502)
![image](https://github.com/user-attachments/assets/78f4c8df-9de5-4183-898f-c08d60c08413)

**Comment by digiserg** [comment]
![image](https://github.com/user-attachments/assets/366e56e5-86de-44a0-b98c-87305c4b6a8d)

**Comment by digiserg** [comment]
`cqlsh` does work from the command line. The only problem seems to be the `tput` warning/error. It may be enough to just ignore it.

**Comment by millerjp** [comment]
@digiserg our cqlsh binary is not intended to work from the command line. @mhmdkrmabd  However, we should look at this as I cant see why it would not also be an issue in workbench

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
@digiserg it should work fine even with the symbol lookup error, is this opened issue because the app doesn't print the right connection error and print the lookup error instead or you're not able to get a successful connection test result?

I've here added the error you've got within the connection test process, and the app was able to do the connection test and give the expected feedback:


https://github.com/user-attachments/assets/48bd3fcc-85e1-4b83-a837-6d8f7ca1bc32

**Comment by digiserg** [comment]
I'll ask the team using Windows to test it again. Can we hide the error?

**Comment by digiserg** [comment]
![image](https://github.com/user-attachments/assets/a2dc9912-999a-404e-bdb3-c8d888fa61dc)

@mhmdkrmabd this is still not working in the latest internal version (20240830)
