### ISSUE TITLE
When leaving CQL console open for a period of time random text appears

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#92]
<img width="1568" alt="Screenshot 2024-07-11 at 17 39 41" src="https://github.com/axonops/axonops-workbench-cassandra/assets/163300/b4d2784d-176e-4ab8-856a-7989d176a348">

**Comment by digiserg** [comment]
I just had this also when scrolling up and down the window.
![image](https://github.com/axonops/axonops-workbench-cassandra/assets/58211930/3d25b505-8883-49da-a219-509ea80ad7c8)

**Comment by digiserg** [comment]
I had this also when scrolling up and down
![image](https://github.com/axonops/axonops-workbench-cassandra/assets/58211930/b4430f7d-1b6a-4be9-b8e9-e6cd1027ef47)

**Comment by mhmdkrmabd** [comment]
@millerjp @digiserg this is happening due to `check connection` process which is the only process performed automatically in the background without the need to user interaction, the way xterm.js is behaving to pause the data flow and prevent showing certain data while it's active seems not efficient, a solution for that is prevent the auto connectivity check process if the basic/standard terminal is opened, otherwise it'll be executed as the terminal will be cleared if the user has entered it so any unwanted output will cleared.

**Comment by millerjp** [comment]
@mhmdkrmabd ok - maybe we should just remove the check connection and error if connections are lost and someone runs a query instead? What would be the impact of doing this?

**Comment by mhmdkrmabd** [comment]
What mostly happen is the cqlsh session will just seem like it has paused, if the user tried to execute a statement it'll just not work, and if he tries to refresh metadata or trace a query for the first time it won't work, the work area will look like it has frozen, but if connection came back things should come back to normal.

Maybe we can implement the approach where checking connectivity is paused if the current active terminal is the basic one, otherwise it'll keep checking the connectivity from time to time, waiting for final decision,
